version: "3"
services:
  webd:
    image: notjeffchan/webd
    container_name: webd-arm64
    environment:
      - TZ=Asia/Shanghai
      - WEB_GUEST=1
      - WEB_USER1=admin
      - WEB_PASS1=admin
      - WEB_USER2=nobody
    volumes:
      - ./data/dir1:/data/dir1
      - ./data/dir2:/data/dir2
    ports:
      - "9090:9212"
    restart: unless-stopped
